
$(eval $(call bsg_fn_build_if_new,dramsim3,$(BP_RTL_BASEJUMP_STL_DIR),$(BP_RTL_TOUCH_DIR)))
%/.dramsim3_build:
	@$(MAKE) -C $(@D)/bsg_test -f libdramsim3.mk
	@$(MV) $(@D)/bsg_test/libdramsim3.so $(BP_RTL_LIB_DIR)/
	@$(CP) $(@D)/imports/DRAMSim3/src/*.h  $(BP_RTL_INCLUDE_DIR)/
	@$(CP) $(@D)/imports/DRAMSim3/ext/headers/*  $(BP_RTL_INCLUDE_DIR)/


