// auto-generated by bsg_ascii_to_rom.py from /home/petrisko/bitbucket/POSH/pre-alpha-release/bp_top/test/rom/rv64ui_p_sub.tr; do not modify
module bp_trace_rom #(parameter width_p=-1, addr_width_p=-1)
(input  [addr_width_p-1:0] addr_i
,output logic [width_p-1:0]      data_o
);
always_comb case(addr_i)
                                 // # Done
   default: data_o = width_p ' (133'b0011_0_0000000000000000000000000000000000000000000000000000000000000000_0000000000000000000000000000000000000000000000000000000000000000); // 0x0600000000000000000000000000000000
endcase
endmodule
