
%/flist.vcs:
	@$(GREP) -v -e "^\#" $(SYN_PATH)/flist.vcs       > $@
	@$(GREP) -v -e "^\#" $(TB_PATH)/$(TB)/flist.vcs >> $@
	@$(SED) -i "s#.*bp_common_pkg.sv#$(BP_COMMON_DIR)/test/common/bp_common_test_pkg.sv#g" $@
	@$(ECHO) wrapper.sv                             >> $@
	@$(ECHO) testbench.sv                           >> $@
	@$(ECHO) "$(BASEJUMP_STL_DIR)/bsg_test/bsg_nonsynth_reset_gen.sv" >> $@
	@$(ECHO) "$(BASEJUMP_STL_DIR)/bsg_test/bsg_nonsynth_clock_gen.sv" >> $@

%/wrapper.sv:
	@$(SED) "s/BP_CFG_FLOWVAR/$(CFG)/g" $(TB_PATH)/$(TB)/$(@F) > $@
	@$(SED) -i 's/BP_DRAM_FLOWVAR/"$(DRAM)"/g' $@

%/testbench.sv:
	@$(SED) "s/BP_CFG_FLOWVAR/$(CFG)/g" $(TB_PATH)/$(TB)/$(@F) > $@
	@$(SED) -i 's/BP_DRAM_FLOWVAR/"$(DRAM)"/g' $@

%/traces:
	$(MKDIR) $(@D)/traces
	$(PYTHON) $(TB_PATH)/$(TB)/trace_script.py $(@D)/traces/

%/test.tr: %/traces
	$(CP) $</$(PROG).tr $@

