
DCACHE_TESTLIST := \
	byte_test \
	word_test \
	double_word_test \
	writeback_test \
	half_word_test \
	unaligned_test \
	uncached_test \
	wt_test_1 \
	wt_test_2 \
	wt_test_3 \
	multicycle_fill_test

ifeq ($(UCE_P),1)
CE := UCE
else
CE := CCE
endif

ifeq ($(WT_P),1)
CA := WT
else
CA := WB
endif

run_testlist.%:
	$(MAKE) build.$* TAG=$(CE).$(CA)
	$(MAKE) $(addsuffix .$*, $(addprefix run_test.$(CE).$(CA).,$(DCACHE_TESTLIST)))

# We can trim this up a bit when we have custom configs
run_test.%:
	$(eval override CE    := $(word 1,$(subst .,  ,$*)))
	$(eval override CA    := $(word 2,$(subst .,  ,$*)))
	$(eval override PROG  := $(word 3,$(subst .,  ,$*)))
	$(eval override TS    := $(word 4,$(subst .,  ,$*)))
	$(MAKE) sim.$(TS) PROG=$(PROG) TAG=$(CE).$(CA)
