blank_issues_enabled: false
contact_links:
  - name: BlackParrot Google Group
    url: https://groups.google.com/g/black-parrot
    about: For more general BlackParrot inquiries. e.g. "I'm trying to do XYZ, what are first steps?"

