HDL_PARAMS=-pvalue+vaddr_width_p=39 			                           \
		   -pvalue+paddr_width_p=56 			                           \
		   -pvalue+asid_width_p=10 				                           \
		   -pvalue+branch_metadata_fwd_width_p=10                          \
		   -pvalue+num_cce_p=1					                           \
		   -pvalue+num_lce_p=1					                           \
		   -pvalue+lce_assoc_p=1				                           \
		   -pvalue+lce_addr_width_p=56			                           \
		   -pvalue+lce_data_width_p=256			                           \
		   -pvalue+boot_rom_els_p=512									   \
		   -pvalue+boot_rom_width_p=512									   \
		   -pvalue+perfect_dcache_p=1
