#ifndef BSG_NEWLIB_FS_H
#define BSG_NEWLIB_FS_H

#include "lfs.h"

// Toplevel filesystem struct
lfs_t bsg_newlib_fs;

// File system configuration structure
// Initalized externally and can be generated by bsg_newlib_mklfs
extern struct lfs_config bsg_newlib_fs_cfg;

// Array with initial LFS image
// Initialized externally and can be generated by bsg_newlib_mklfs
extern uint8_t lfs_mem[];

// Exit routine: exit() calls this routine
// Definition provided externally by user
extern void bsg_newlib_exit(int);

// Utility to print a char to console
// Definition provided externally by user
extern void bsg_newlib_sendchar(char);

// LFS init routine: Should be called before calling main
int bsg_newlib_fs_init(void);

#endif // BSG_NEWLIB_FS_H
