TOP            = $(CURDIR)/../../..
BP_TOP_PATH	   = $(TOP)/bp_top
BP_FE_PATH	   = $(TOP)/bp_fe
BP_BE_PATH	   = $(TOP)/bp_be
BP_ME_PATH 	   = $(TOP)/bp_me
BP_COMMON_PATH = $(TOP)/bp_common

BSG_IP_PATH	   = $(TOP)/bsg_ip_cores

TB_DIR         = $(BP_BE_PATH)/test
ASM_DIR        = $(TB_DIR)/asm
ROM_DIR        = $(TB_DIR)/rom
TRACE_ROM_DIR  = $(TB_DIR)/trace_rom

HEX2BIN        = $(BP_BE_PATH)/software/py/hex2binascii.py
SPIKE2TR        = $(BP_BE_PATH)/software/py/spike2tr.py
BSG_ROM_GEN    = $(BSG_IP_PATH)/bsg_mem/bsg_ascii_to_rom.py
RISCV_ELF2HEX  = elf2hex
RISCV_SIM	   = spike
RISCV_OBJDUMP  = riscv64-unknown-elf-objdump -D -M no-aliases,numeric

include $(ASM_DIR)/Makefile.frag

all: bp-demo-roms

bp-demo-roms: $(foreach x, $(subst -,_,$(BP_DEMOS)),$(x).v)

# TODO: This needs some serious clean-up later
%.v: %.bin
	python $(BSG_ROM_GEN) $< bp_be_boot_rom zero > $*.vtmp 			             \
	&& awk 'FNR==2{system("$(RISCV_OBJDUMP) $*.elf | sed 's-^-//-'")} 1' $*.vtmp   \
		> $(ROM_DIR)/$*_rom.v 													     \
	&& rm $*.vtmp

%.bin: %.hex
	python $(HEX2BIN) $< 512 > $@

%.hex: %.elf
	$(RISCV_ELF2HEX) 16 32768 $< 2147483648  > $@

%.elf:
	make -C $(ASM_DIR)/demos $*.elf
	mv $(ASM_DIR)/demos/$@ $@
##########################################
