CCE_TRACE_P    ?= 0
LCE_TRACE_P    ?= 0
DRAM_TRACE_P   ?= 0
ICACHE_TRACE_P ?= 0
UCE_P          ?= 0

export BP_SIM_CLK_PERIOD ?= 1000

export DUT_PARAMS = 
export TB_PARAMS  = -pvalue+uce_p=$(UCE_P) \
                    -pvalue+cce_trace_p=$(CCE_TRACE_P)   \
                    -pvalue+lce_trace_p=$(LCE_TRACE_P)   \
                    -pvalue+dram_trace_p=$(DRAM_TRACE_P) \
                    -pvalue+icache_trace_p=$(ICACHE_TRACE_P) \
                    -pvalue+dram_fixed_latency_p=$(DRAM_FIXED_LATENCY)

export DUT_DEFINES =
export TB_DEFINES  = +define+BP_SIM_CLK_PERIOD=$(BP_SIM_CLK_PERIOD) \
                     +define+den2048Mb+sg5+x16+FULL_MEM

export HDL_DEFINES = $(DUT_DEFINES) $(TB_DEFINES)
export HDL_PARAMS  = $(DUT_PARAMS) $(TB_PARAMS)

