
BUILD_COLLATERAL += flist.vcs

ifneq (,$(COH_PROTO))
CCE_UCODE ?= $(BP_INSTALL_DIR)/lib/$(COH_PROTO).mem
else
CCE_UCODE ?= $(TB_PATH)/demo_ucode.mem
endif

ifneq (,$(SUITE)$(PROG))
SIM_PROG ?= $(BP_RISCV_DIR)/$(addsuffix /,$(SUITE))$(PROG).riscv
else
SIM_PROG ?= $(TB_PATH)/demo.riscv
endif

%/ucode.mem: $(CCE_UCODE)
	@$(MKDIR) -p $(@D)
	@$(CP) $< $@

%/prog.riscv: $(SIM_PROG)
	@$(MKDIR) -p $(@D)
	@$(CP) $< $@

ifneq (00,$(DROMAJO_COSIM)$(SPIKE_COSIM))
RUN_COLLATERAL += prog.riscv
PLUSARGS += +elf_file=prog.riscv
endif

ifeq (1,$(DISASSEMBLE))
RUN_COLLATERAL += prog.dump
endif

ifeq (1,$(CFG_UCODE))
RUN_COLLATERAL += ucode.mem
PLUSARGS += +ucode_mem=ucode.mem
endif

RUN_COLLATERAL += prog.mem
PLUSARGS += +init_mem=prog.mem

ifeq (1,$(SPIKE_TRACE))
RUN_COLLATERAL += spike.trace
endif

ifeq (1,$(DROMAJO_TRACE))
RUN_COLLATERAL += dromajo.trace
endif

include $(BP_MK_DIR)/Makefile.collateral

