$(LINT_DIR)/testbench.v $(LINT_DIR)/wrapper.v $(LINT_DIR)/test_bp.cpp:
	@sed "s/BP_CFG_FLOWVAR/$(CFG)/g" $(TB_PATH)/$(TB)/$(@F) > $@

$(LINT_DIR)/flist.vcs:
	@grep -v -e "^\#" $(SYN_PATH)/flist.vcs       > $@ 
	@grep -v -e "^\#" $(TB_PATH)/$(TB)/flist.vcs >> $@ 
	@echo wrapper.v                              >> $@ 
	@echo testbench.v                            >> $@ 
	@echo test_bp.cpp                            >> $@ 

$(LINT_DIR)/config.vlt:
	cat $(SYN_PATH)/lint_settings.verilator | envsubst > $@

$(LINT_DIR)/bootrom.riscv: $(BP_TEST_MEM_DIR)/bootrom.riscv
	cp $^ $@

XXD ?= xxd
AWK ?= awk
$(LINT_DIR)/bootrom.txt: $(LINT_DIR)/bootrom.bin
	$(XXD) -b -c 4 $< | $(AWK) '{print $$2$$3$$4$$5}' > $@

$(LINT_DIR)/bp_bootrom.v: $(LINT_DIR)/bootrom.txt
	$(PYTHON) $(BASEJUMP_STL_DIR)/bsg_mem/bsg_ascii_to_rom.py $< bp_bootrom > $@

LINT_COLLATERAL  = $(addprefix $(LINT_DIR)/, config.vlt flist.vcs wrapper.v testbench.v test_bp.cpp)
LINT_COLLATERAL += $(addprefix $(LINT_DIR)/, bootrom.riscv bootrom.bin bootrom.dump bp_bootrom.v)

$(BUILD_DIR)/testbench.v $(BUILD_DIR)/wrapper.v $(BUILD_DIR)/test_bp.cpp:
	@sed "s/BP_CFG_FLOWVAR/$(CFG)/g" $(TB_PATH)/$(TB)/$(@F) > $@

$(BUILD_DIR)/flist.vcs:
	@grep -v -e "^\#" $(SYN_PATH)/flist.vcs       > $@ 
	@grep -v -e "^\#" $(TB_PATH)/$(TB)/flist.vcs >> $@ 
	@echo wrapper.v                              >> $@ 
	@echo testbench.v                            >> $@ 
	@echo test_bp.cpp                            >> $@ 

$(BUILD_DIR)/config.vlt:
	cat $(SYN_PATH)/lint_settings.verilator | envsubst > $@

$(BUILD_DIR)/bootrom.riscv: $(BP_TEST_MEM_DIR)/bootrom.riscv
	cp $^ $@

XXD ?= xxd
AWK ?= awk
$(BUILD_DIR)/bootrom.txt: $(BUILD_DIR)/bootrom.bin
	$(XXD) -b -c 4 $< | $(AWK) '{print $$2$$3$$4$$5}' > $@

$(BUILD_DIR)/bp_bootrom.v: $(BUILD_DIR)/bootrom.txt
	$(PYTHON) $(BASEJUMP_STL_DIR)/bsg_mem/bsg_ascii_to_rom.py $< bp_bootrom > $@

VBUILD_COLLATERAL  = $(addprefix $(BUILD_DIR)/, config.vlt flist.vcs wrapper.v testbench.v test_bp.cpp)
VBUILD_COLLATERAL += $(addprefix $(BUILD_DIR)/, bootrom.riscv bootrom.bin bootrom.dump bp_bootrom.v)
CBUILD_COLLATERAL = none

$(SIM_DIR)/simsc: $(BUILD_DIR)/obj_dir
	@ln -nsf $</simsc $@

$(SIM_DIR)/prog.riscv: $(BP_TEST_MEM_DIR)/$(SUITE)/$(PROG).riscv
	@cp $^ $@

$(SIM_DIR)/prog.elf: $(BP_TEST_MEM_DIR)/$(SUITE)/$(PROG).riscv
	cp $^ $@

$(SIM_DIR)/cce_ucode.mem: $(CCE_MEM_PATH)/$(CCE_MEM)
	@cp $^ $@

$(SIM_DIR)/dram_ch.ini $(SIM_DIR)/dram_sys.ini:
	@cp $(BP_COMMON_DIR)/test/cfg/$(DRAMSIM_CH_CFG) $(@D)/dram_ch.ini
	@cp $(BP_COMMON_DIR)/test/cfg/$(DRAMSIM_SYS_CFG) $(@D)/dram_sys.ini

NBF_INPUTS = $(NCPUS)
NBF_INPUTS += cce_ucode.mem
ifeq ($(PRELOAD_MEM_P), 0)
	NBF_INPUTS += --mem=prog.mem
endif

$(SIM_DIR)/prog.nbf: $(SIM_DIR)/cce_ucode.mem $(SIM_DIR)/prog.mem
	cd $(@D); python $(MEM2NBF) $(NBF_INPUTS) > $@

$(SIM_DIR)/bootrom.riscv: $(BP_TEST_MEM_DIR)/bootrom.riscv
	cp $^ $@

$(SIM_DIR)/bootrom.mem: $(SIM_DIR)/bootrom.bin
	$(RISCV_OBJCOPY) -I binary $< -O verilog --verilog-data-width=4 $@

SIM_COLLATERAL  = $(addprefix $(SIM_DIR)/, simsc)
SIM_COLLATERAL += $(addprefix $(SIM_DIR)/, prog.riscv prog.elf prog.mem prog.nbf prog.dump)
SIM_COLLATERAL += $(addprefix $(SIM_DIR)/, cce_ucode.mem)
SIM_COLLATERAL += $(addprefix $(SIM_DIR)/, dram_ch.ini dram_sys.ini)
SIM_COLLATERAL += $(addprefix $(SIM_DIR)/, bootrom.riscv bootrom.bin bootrom.mem bootrom.dump)

sim_sample.sc: build.sc
sim_sample.sc: $(SIM_DIR)/run_samplesc
sim_sample.sc: SIM_LOG    := $(LOG_DIR)/$(TB).$(CFG).$(TAG).sim.$(SUITE).$(PROG).log
sim_sample.sc: SIM_REPORT := $(REPORT_DIR)/$(TB).$(CFG).$(TAG).sim.$(SUITE).$(PROG).rpt
sim_sample.sc: SIM_ERROR  := $(REPORT_DIR)/$(TB).$(CFG).$(TAG).sim.$(SUITE).$(PROG).err
$(SIM_DIR)/run_samplesc: $(SIM_COLLATERAL)
	cd $(@D); \
		$(DROMAJO) $(@D)/prog.riscv --host --ncpus=$(NCPUS) --maxinsn=$(SAMPLE_START_P) --save=dromajo --memory_size=$(SAMPLE_MEMSIZE)
	mv $(@D)/dromajo.*.mainram $(@D)/prog.mainram
	mv $(@D)/dromajo.*.bootram $(@D)/prog.bootram
	mv $(@D)/dromajo.*.bp_regs $(@D)/prog.bp_regs
	$(RISCV_OBJCOPY) --change-addresses 0x80000000 -I binary -O elf64-littleriscv -B riscv \
		$(@D)/prog.mainram $(@D)/prog.riscv
	$(RISCV_OBJCOPY) -O verilog $(@D)/prog.riscv $(@D)/prog.mem
	cd $(@D); \
		python $(MEM2NBF) $(NBF_INPUTS) --checkpoint=prog.bp_regs > prog.nbf
	cd $(@D); \
		./simsc $(VERILATOR_OPTIONS) $(VERILATOR_PLUSARGS) | tee $(SIM_LOG)
	-@grep "PASS" $(SIM_LOG) || echo "FAILED" > $(SIM_ERROR)
	-@grep "STATS" -A 3 $(SIM_LOG) > $(SIM_REPORT)

tire_kick: $(SIM_DIR)/tire_kick
tire_kick: $(SIM_DIR)/simsc
$(SIM_DIR)/tire_kick: $(TOUCH_DIR) $(RESULTS_DIR) $(LOG_DIR) $(REPORT_DIR) $(SIM_DIR)
	$(MAKE) build.sc
	$(MAKE) $(@D)/simsc
	cp $(BP_TEST_MEM_DIR)/hello_world.mem  $(@D)/prog.mem
	cp $(BP_TEST_MEM_DIR)/hello_world.dump $(@D)/prog.dump
	cp $(CCE_MEM_PATH)/$(CCE_MEM) $(@D)/cce_ucode.mem
	cd $(@D); ./simsc $(VERILATOR_OPTIONS) $(VERILATOR_PLUSARGS)

