$(BUILD_DIR)/flist.vcs:
	grep -v -e "^\#" $(SYN_PATH)/flist.vcs       > $@
	echo wrapper.sv                             >> $@

$(BUILD_DIR)/wrapper.v:
	@sed "s/BP_CFG_FLOWVAR/$(CFG)/g" $(TB_PATH)/$(TB)/$(@F) > $@

SYNTH_COLLATERAL = $(addprefix $(BUILD_DIR)/, flist.vcs wrapper.sv)

