$(BUILD_DIR)/flist.vcs:
	grep -v -e "^\#" $(SYN_PATH)/flist.vcs       > $@ 
	echo wrapper.sv                             >> $@

$(BUILD_DIR)/wrapper.sv:
	@sed "s/BP_CFG_FLOWVAR/$(CFG)/g" $(TB_PATH)/$(TB)/$(@F) > $@

CHK_COLLATERAL = $(addprefix $(BUILD_DIR)/, flist.vcs wrapper.sv)

