e_bp_unicore_writethrough_cfg_cores    := 1
e_bp_single_core_l1_medium_cfg_cores   := 1
e_bp_single_core_l1_small_cfg_cores    := 1
e_bp_unicore_l1_medium_cfg_cores       := 1
e_bp_unicore_l1_small_cfg_cores        := 1
e_bp_sexta_core_cce_ucode_cfg_cores    := 16
e_bp_twelve_core_cce_ucode_cfg_cores   := 12
e_bp_oct_core_cce_ucode_cfg_cores      := 8
e_bp_hexa_core_cce_ucode_cfg_cores     := 6
e_bp_quad_core_cce_ucode_cfg_cores     := 4
e_bp_tri_core_cce_ucode_cfg_cores      := 3
e_bp_dual_core_cce_ucode_cfg_cores     := 2
e_bp_single_core_cce_ucode_cfg_cores   := 1
e_bp_half_core_cce_ucode_cfg_cores     := 1
e_bp_accelerator_quad_core_cfg_cores   := 4
e_bp_accelerator_single_core_cfg_cores := 1
e_bp_sexta_core_cfg_cores              := 16
e_bp_twelve_core_cfg_cores             := 12
e_bp_oct_core_cfg_cores                := 8
e_bp_hexa_core_cfg_cores               := 6
e_bp_quad_core_cfg_cores               := 4
e_bp_tri_core_cfg_cores                := 3
e_bp_dual_core_cfg_cores               := 2
e_bp_single_core_cfg_cores             := 1
e_bp_single_core_no_l2_cfg_cores       := 1
e_bp_half_core_cfg_cores               := 1
e_bp_unicore_cfg_cores                 := 1
e_bp_unicore_no_l2_cfg_cores           := 1


export NCPUS ?= $($(CFG)_cores)

ifeq ($(origin $(CFG)_cores), undefined)
$(error NCPUS not found for CFG=$(CFG))
endif
