$(SYNTH_DIR)/flist.vcs:
	grep -v -e "^\#" $(SYN_PATH)/flist.vcs       > $@
	echo wrapper.sv                             >> $@

$(SYNTH_DIR)/wrapper.sv:
	sed "s/BP_CFG_FLOWVAR/$(CFG)/g" $(TB_PATH)/$(TB)/$(@F) > $@

$(SYNTH_DIR)/design.xdc:
	cp $(TB_PATH)/$(TB)/$(@F) $@

SYNTH_COLLATERAL = $(addprefix $(SYNTH_DIR)/, flist.vcs wrapper.sv design.xdc)
