
PERF_ENABLE_P         ?= 1
WARMUP_INSTR_P        ?= 0
MAX_INSTR_P           ?= 10000000
MAX_CYCLE_P           ?= 10000000

WATCHDOG_ENABLE_P     ?= 1
STALL_CYCLES_P        ?= 100000
HALT_INSTR_P          ?= 1000
HEARTBEAT_INSTR_P     ?= 10000

COSIM_TRACE_P         ?= $(COMMITLOG)
COSIM_CHECK_P         ?= $(if $(or $(filter 1,$(DROMAJO_COSIM)),$(filter 1,$(SPIKE_COSIM))),1,0)

HDL_DEFINES += \
	+define+BP_CFG_FLOWVAR=$(CFG)

HDL_PARAMS += \
	-pvalue+perf_enable_p=$(PERF_ENABLE_P) \
	-pvalue+warmup_instr_p=$(WARMUP_INSTR_P) \
	-pvalue+max_instr_p=$(MAX_INSTR_P) \
	-pvalue+max_cycle_p=$(MAX_CYCLE_P) \
	\
	-pvalue+watchdog_enable_p=$(WATCHDOG_ENABLE_P) \
	-pvalue+stall_cycles_p=$(STALL_CYCLES_P) \
	-pvalue+halt_instr_p=$(HALT_INSTR_P) \
	-pvalue+heartbeat_instr_p=$(HEARTBEAT_INSTR_P) \
	\
	-pvalue+cosim_trace_p=$(COSIM_TRACE_P) \
	-pvalue+cosim_check_p=$(COSIM_CHECK_P)

include $(BP_MK_DIR)/Makefile.params

