# compute number of cores from config
_MULTICORE := $(findstring e_bp_multicore, $(CFG))
ifeq ($(_MULTICORE),)
	export NCPUS ?= 1
else
	# requires multicore configs to be named: e_bp_multicore_NCPUS_[*_]cfg
	_NCPUS := $(strip $(word 4, $(subst _, ,$(CFG))))
	export NCPUS ?= $(_NCPUS)
endif

e_bp_unicore_tinyparrot_cfg_amoen := 0

_AMOEN :=$($(CFG)_amoen)
ifeq ($(_AMOEN),)
	export AMOEN ?= 1
else
	export AMOEN ?= $(_AMOEN)
endif

e_bp_unicore_paddr_large_cfg_paddr_width               := 44
e_bp_multicore_1_paddr_large_cfg_paddr_width           := 44
e_bp_multicore_1_cce_ucode_paddr_large_cfg_paddr_width := 44

e_bp_unicore_tinyparrot_cfg_paddr_width                := 33
e_bp_unicore_paddr_small_cfg_paddr_width               := 33
e_bp_multicore_1_paddr_small_cfg_paddr_width           := 33
e_bp_multicore_1_cce_ucode_paddr_small_cfg_paddr_width := 33

e_bp_default_cfg_paddr_width                           := 40

_PADDR_WIDTH :=$($(CFG)_paddr_width)
ifeq ($(_PADDR_WIDTH),)
	export PADDR_WIDTH ?= 40
else
	export PADDR_WIDTH ?= $(_PADDR_WIDTH)
endif

e_bp_custom_cfg_ucode := 1
$(CFG)_ucode ?= $(findstring cce_ucode,$(CFG))

_UCODE ?= $($(CFG)_ucode)
ifeq ($(_UCODE),)
	export UCODE ?= 0
else
	export UCODE ?= 1
endif

