export COH_PROTO   ?= mesi
export CCE_MEM_PATH = $(BP_ME_DIR)/src/asm/roms
export CCE_MEM      = $(COH_PROTO).mem

export CCE_TRACE_P    ?= 0
export LCE_TRACE_P    ?= 0
export CMT_TRACE_P    ?= 0
export DRAM_TRACE_P   ?= 0
export ICACHE_TRACE_P ?= 0
export DCACHE_TRACE_P ?= 0
export NPC_TRACE_P    ?= 0
export VM_TRACE_P     ?= 0
export CORE_PROFILE_P ?= 0
export CHECKPOINT_P   ?= 0
export COSIM_P        ?= 0
export PRELOAD_MEM_P  ?= 0

export DOMAINS_P      ?= '00000001'
export SAC_P          ?= 0

export SAMPLE_MEMSIZE   ?= 128
export SAMPLE_START_P   ?= 0
export SAMPLE_WARMUP_P  ?= 0
export SAMPLE_INSTR_P   ?= 0

export DRAM_PKG = bsg_dramsim3_hbm2_4gb_x128_pkg

export DRAM_FIXED_LATENCY ?= 10
export BP_SIM_CLK_PERIOD ?= 1000

export DUT_PARAMS = 
export TB_PARAMS  = \
                    -pvalue+cce_trace_p=$(CCE_TRACE_P)   \
                    -pvalue+lce_trace_p=$(LCE_TRACE_P)   \
                    -pvalue+cmt_trace_p=$(CMT_TRACE_P)   \
                    -pvalue+dram_trace_p=$(DRAM_TRACE_P) \
                    -pvalue+icache_trace_p=$(ICACHE_TRACE_P) \
                    -pvalue+dcache_trace_p=$(DCACHE_TRACE_P) \
                    -pvalue+npc_trace_p=$(NPC_TRACE_P) \
                    -pvalue+vm_trace_p=$(VM_TRACE_P) \
                    -pvalue+core_profile_p=$(CORE_PROFILE_P) \
                    -pvalue+checkpoint_p=$(CHECKPOINT_P) \
                    -pvalue+cosim_p=$(COSIM_P) \
                    -pvalue+cosim_memsize_p=$(SAMPLE_MEMSIZE) \
                    -pvalue+cosim_instr_p=$(SAMPLE_INSTR_P) \
                    -pvalue+warmup_instr_p=$(SAMPLE_WARMUP_P) \
                    -pvalue+preload_mem_p=$(PRELOAD_MEM_P) \
                    -pvalue+dram_fixed_latency_p=$(DRAM_FIXED_LATENCY)

export DUT_DEFINES = 
export TB_DEFINES  = +define+BP_SIM_CLK_PERIOD=$(BP_SIM_CLK_PERIOD) \
                     +define+dram_pkg=$(DRAM_PKG)

export HDL_DEFINES = $(DUT_DEFINES) $(TB_DEFINES)
export HDL_PARAMS  = $(DUT_PARAMS) $(TB_PARAMS)

