// auto-generated by bsg_ascii_to_rom.py from /home/petrisko/bitbucket/pre-alpha-release/bp_top/test/rom/multiply.tr; do not modify
module bp_trace_rom #(parameter width_p=-1, addr_width_p=-1)
(input  [addr_width_p-1:0] addr_i
,output logic [width_p-1:0]      data_o
);
always_comb case(addr_i)
                                 // # Send format: 		0001_pc(64 bit)_instruction(32 bit)
                                 // # Receive formats:
                                 // # Register write:	0010_0_rd(5 bit)_data(64 bit)
                                 // # Memory write:		0010_1_addr(64 bit)_data(64 bit)
                                 // # Done
         0: data_o = width_p ' (133'b0011_0_0000000000000000000000000000000000000000000000000000000000000000_0000000000000000000000000000000000000000000000000000000000000000); // 0x0600000000000000000000000000000000
   default: data_o = { width_p { 1'b0 } };
endcase
endmodule
