// auto-generated by bsg_ascii_to_rom.py from /home/petrisko/bitbucket/pre-alpha-release/bp_fe/test/rom/median.tr; do not modify
module bp_trace_rom #(parameter width_p=-1, addr_width_p=-1)
(input  [addr_width_p-1:0] addr_i
,output logic [width_p-1:0]      data_o
);
always_comb case(addr_i)
                                 // # Trace format: recv (4bit)_pc          (64 bit)_instruction(32 bits)
                                 // #               send (4bit)_branchtarget(64 bit)_branchtaken(1   bit)_padding(31 bits)
                                 // # 	 branch target: 0x0000000080000124	 branch taken: 0
                                 // # Done
     default: data_o = width_p ' (100'b0011_0000000000000000000000000000000000000000000000000000000000000000_00000000000000000000000000000000); // 0x3000000000000000000000000
endcase
endmodule
