// auto-generated by bsg_ascii_to_rom.py from /home/petrisko/bitbucket/pre-alpha-release/bp_fe/test/rom/rv64ui_p_add.tr; do not modify
module bp_trace_rom #(parameter width_p=-1, addr_width_p=-1)
(input  [addr_width_p-1:0] addr_i
,output logic [width_p-1:0]      data_o
);
always_comb case(addr_i)
                                 // # Trace format: recv (4bit)_pc          (64 bit)_instruction(32 bits)
