UCE_P          ?= 0

export BP_SIM_CLK_PERIOD ?= 1000

export DUT_PARAMS =
export TB_PARAMS  = -pvalue+uce_p=$(UCE_P)

export DUT_DEFINES = $(foreach def,$(DEFINES),+define+$(def))
export TB_DEFINES  = +define+BP_SIM_CLK_PERIOD=$(BP_SIM_CLK_PERIOD) \
                     +define+den2048Mb+sg5+x16+FULL_MEM

export HDL_DEFINES = $(DUT_DEFINES) $(TB_DEFINES)
export HDL_PARAMS  = $(DUT_PARAMS) $(TB_PARAMS)

