$(BUILD_DIR)/flist.vcs:
	grep -v -e "^\#" $(SYN_PATH)/flist.vcs       > $@
	@sed -i "s#.*bp_common_pkg.sv#$(BP_COMMON_DIR)/test/common/bp_common_test_pkg.sv#g" $@
	echo wrapper.sv                             >> $@

$(BUILD_DIR)/wrapper.sv:
	@sed "s/BP_CFG_FLOWVAR/$(CFG)/g" $(TB_PATH)/$(TB)/$(@F) > $@

CHK_COLLATERAL = $(addprefix $(BUILD_DIR)/, flist.vcs wrapper.sv)
