e_bp_multicore_cce_ucode_half_cfg_lces := 1
e_bp_multicore_half_cfg_lces           := 1
e_bp_unicore_half_cfg_lces             := 1

e_bp_multicore_16_cce_ucode_cfg_lces   := 32
e_bp_multicore_16_cfg_lces             := 32
e_bp_multicore_12_cce_ucode_cfg_lces   := 24
e_bp_multicore_12_cfg_lces             := 24
e_bp_multicore_8_cce_ucode_cfg_lces    := 16
e_bp_multicore_8_cfg_lces              := 16
e_bp_multicore_6_cce_ucode_cfg_lces    := 12
e_bp_multicore_6_cfg_lces              := 12
e_bp_multicore_4_accelerator_cfg_lces  := 8
e_bp_multicore_4_cce_ucode_cfg_lces    := 8
e_bp_multicore_4_cfg_lces              := 8
e_bp_multicore_3_cce_ucode_cfg_lces    := 6
e_bp_multicore_3_cfg_lces              := 6
e_bp_multicore_2_cce_ucode_cfg_lces    := 4
e_bp_multicore_2_cfg_lces              := 4
e_bp_multicore_1_accelerator_cfg_lces  := 2
e_bp_multicore_1_cce_ucode_cfg_lces    := 2
e_bp_multicore_1_l1_medium_cfg_lces    := 2
e_bp_multicore_1_l1_small_cfg_lces     := 2
e_bp_multicore_1_cfg_lces              := 2

e_bp_unicore_writethrough_cfg_lces     := 2
e_bp_unicore_l1_medium_cfg_lces        := 2
e_bp_unicore_l1_small_cfg_lces         := 2
e_bp_unicore_no_l2_cfg_lces            := 2
e_bp_unicore_cfg_lces                  := 2

# Note, custom must be manually overidden here for cosim to work properly
e_bp_custom_cfg_lces                   := 2
e_bp_default_cfg_lces                  := 2

export NUM_LCE_P ?= $($(CFG)_lces)

ifeq ($(origin $(CFG)_lces), undefined)
$(error NUM_LCE_P not found for CFG=$(CFG))
endif
