export NUM_INSTR_P ?= 4096
SEED_P ?= 1

# mode and cached/uncached settings
# CCE_MODE_P controls whether the CCE operates in normal or uncached only mode
# CCE_MODE_P: 0 = CCE normal mode, 1 = CCE uncached only mode
# if CCE_MODE_P == 1, then LCE_MODE_P must be 1
export CCE_MODE_P ?= 0
# LCE_MODE_P controls whether the LCE issues cached, uncached, or both requests
# this parameter is only used by the trace rom script, not by the LCE hardware, so it is
#   not added to TB_PARAMS
# LCE_MODE_P: 0 = cached requests, 1 = uncached requests, 2 = both requests
export LCE_MODE_P ?= 0
# Test to run
# 0 = random loads and stores
# 1 = cached store test
# 2 = cached store->load test
# 3 = cached set test
# 4 = cached block test
# 5 = cache hammer test
# 6 = AXE test
export ME_TEST_P ?= 0

export MEM_BLOCKS_P ?= 0

export ME_DEBUG_P ?= 0

ifeq ($(ME_DEBUG_P),1)
export ME_DEBUG_FLAG = --debug
else
export ME_DEBUG_FLAG =
endif

COH_PROTO   ?= mesi
CCE_MEM      = $(COH_PROTO).mem

export BP_SIM_CLK_PERIOD ?= 1000

ifeq ($(ME_TEST_P),6)
export AXE_TRACE_P = 1
else
export AXE_TRACE_P = 0
endif
export CCE_TRACE_P ?= 0
export CCE_DIR_TRACE_P ?= 0
export LCE_TRACE_P ?= 0
export LCE_TR_TRACE_P ?= 0
export DRAM_TRACE_P ?= 0

export DUT_PARAMS =
export TB_PARAMS  = \
    -pvalue+axe_trace_p=$(AXE_TRACE_P) \
    -pvalue+cce_trace_p=$(CCE_TRACE_P) \
    -pvalue+cce_dir_trace_p=$(CCE_TRACE_P) \
    -pvalue+instr_count=$(NUM_INSTR_P) \
    -pvalue+cce_mode_p=$(CCE_MODE_P) \
    -pvalue+lce_trace_p=$(LCE_TRACE_P) \
    -pvalue+lce_tr_trace_p=$(LCE_TR_TRACE_P) \
    -pvalue+dram_trace_p=$(DRAM_TRACE_P) \

export DUT_DEFINES = $(foreach def,$(DEFINES),+define+$(def))
export TB_DEFINES  = +define+BP_SIM_CLK_PERIOD=$(BP_SIM_CLK_PERIOD) \
					 +define+den2048Mb+sg5+x16+FULL_MEM

export HDL_DEFINES = $(DUT_DEFINES) $(TB_DEFINES)
export HDL_PARAMS  = $(DUT_PARAMS) $(TB_PARAMS)

